vim.keymap.set('n', '<leader>rr', function()
    vim.cmd('Rest run')
end)
vim.keymap.set('n', '<leader>rl', function()
    vim.cmd('Rest last')
end)
vim.keymap.set('n', '<leader>ro', function()
    vim.cmd('Rest open')
end)
